services:
  mongodb:
    image: mongo:6.0.4
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
